### ISSUE TITLE
Segmentation Fault on KeyboardInterrupt

### ISSUE THREAD

**Issue by mfgarvin** [mfgarvin/DOC_Mapboard#3]
Likely related to #2 
I've attempted to catch KeyboardInterrupts at various points in the code (mainly in threads), though I'm unable to catch them and quit the code cleanly. I've probably implemented threading incorrectly.

Upon Ctrl-C:

> `Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
Segmentation fault >

**Comment by tcgarvin** [comment]
I don't know how to do this cleanly either.  Every time I google it, it
seems like too much work
